/**
 * Worker spawning that survives `bun build --compile`.
 *
 * Bun standalone executables fail to resolve nested worker entrypoints
 * (oven-sh/bun#29124): the main bundle is flattened into /$bunfs/root while
 * additional entrypoints keep their nested paths, so `new Worker(new URL(...))`
 * dies with ModuleNotFound in compiled binaries. Standalone builds therefore
 * embed each worker as a pre-bundled source string (generated by
 * scripts/build-standalone.ts into src/generated/worker-bundles.gen.ts) and
 * spawn it from a Blob URL, which works in both compiled binaries and source
 * checkouts. Source checkouts without generated bundles fall back to the
 * dev-mode URL form.
 */
import { WORKER_BUNDLES } from "./generated/worker-bundles.gen";

export function spawnWorker(devUrl: string, key: string): Worker {
  const src = WORKER_BUNDLES[key];
  if (src) {
    return new Worker(URL.createObjectURL(new Blob([src], { type: "text/javascript" })));
  }
  return new Worker(devUrl);
}
